name: Generate Convex Types

on:
  workflow_dispatch:  # Manual trigger only
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Convex schema and types
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
        run: |
          npx convex env set CLERK_DOMAIN ${{ secrets.CLERK_DOMAIN }}
          npx convex env set OPENROUTER_API_KEY ${{ secrets.OPENROUTER_API_KEY }}
          npx convex codegen
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit generated files
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add convex/_generated/
          git commit -m "Update Convex generated types [skip ci]
          
          Generated by GitHub Action on $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
      
      - name: No changes detected
        if: steps.verify-changed-files.outputs.changed == 'false'
        run: echo "No changes detected in generated files"