name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger

jobs:
  convex-codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Convex schema and types
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
        run: |
          npx convex env set CLERK_DOMAIN ${{ secrets.CLERK_DOMAIN }}
          npx convex env set OPENROUTER_API_KEY ${{ secrets.OPENROUTER_API_KEY }}
          npx convex codegen
      
      - name: Commit generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add convex/_generated/
          git diff --staged --quiet || git commit -m "Update Convex generated types [skip ci]"
          git push
        continue-on-error: true

  deploy:
    needs: convex-codegen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # Get latest with codegen changes
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Build and deploy
        run: |
          eas build --platform all --non-interactive